# Generated by Django 6.1 on 2026-09-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_avatar_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='car_model',
            field=models.CharField(blank=True, help_text='напр. Mercedes-Benz S 63', max_length=100, null=True, verbose_name='Автомобил (Марка и модел)'),
        ),
    ]
